#!/usr/bin/env python3

import click
from commands import sonarr
from commands import radarr

@click.group()
def cli():
    """Homelab Infrastructure CLI"""
    pass

cli.add_command(sonarr.sonarr)
cli.add_command(radarr.radarr)

if __name__ == "__main__":
    cli()
