#!/usr/bin/env python3

import click
from commands import sonarr
from commands import radarr
from commands import bazarr
from commands import prowlarr


@click.group()
def cli():
    """Homelab Infrastructure CLI"""
    pass

cli.add_command(sonarr.sonarr)
cli.add_command(radarr.radarr)
cli.add_command(bazarr.bazarr)
cli.add_command(prowlarr.prowlarr)

if __name__ == "__main__":
    cli()
